version: "3.8"
services:
  icat-based:
    image: irods-icat:latest
    depends_on:
      - irods-db
    hostname: irods.dh.local
    ports:
      - "1247:1247"
      - "1248:1248"
    environment:
      RODS_PASSWORD: irods
      PGPASSWORD: foobar
      VIRTUAL_HOST: irods.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: ${ENV_IRODS_INGEST_REMOVE_DELAY}
      MIRTH_VALIDATION_CHANNEL: ${ENV_MIRTH_VALIDATION_CHANNEL}
      MIRTH_METADATA_CHANNEL: ${ENV_MIRTH_METADATA_CHANNEL}
      LOGSPOUT: ignore  #ignore, because logs are forwarded by filebeat (in production it's not in a docker container)
    networks:
      default:
        aliases:
          - irods.dh.local
      common_default:
        aliases:
          - irods.dh.local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./externals/irods-ruleset:/rules
      - ./externals/irods-microservices:/microservices
      - ./keycloak/users.json:/opt/irods/users.json

  ires-based:
    image: irods-ires:latest
    depends_on:
      - irods-db
    hostname: ires.dh.local
    environment:
      RODS_PASSWORD: irods
      PGPASSWORD: foobar
      VIRTUAL_HOST: irods.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: ${ENV_IRODS_INGEST_REMOVE_DELAY}
      MIRTH_VALIDATION_CHANNEL: ${ENV_MIRTH_VALIDATION_CHANNEL}
      MIRTH_METADATA_CHANNEL: ${ENV_MIRTH_METADATA_CHANNEL}
      LOGSPOUT: ignore  #ignore, because logs are forwarded by filebeat (in production it's not in a docker container)
    networks:
      default:
        aliases:
          - ires.dh.local
      common_default:
        aliases:
          - ires.dh.local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./irods.secrets.cfg:/etc/secrets:ro
      - ./externals/irods-ruleset:/rules
      - ./externals/irods-microservices:/microservices
      - ./externals/irods-helper-cmd:/helpers
      - ./staging-data:/mnt/ingest            # binding a non-existing dir results in creation of that dir on host system
    # Required for CIFS mounting. cap-add not enough in Windows for some reason.
    privileged: true

  ires-s3-1-based:
    image: irods-ires-s3:latest
    depends_on:
      - icat-based
      - ires-based  # Because of ingest resource
      - minio1
    hostname: ires-s3-1.dh.local
    environment:
      RODS_PASSWORD: irods
      VIRTUAL_HOST: ires-s3-1.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: ${ENV_IRODS_INGEST_REMOVE_DELAY}
      MIRTH_VALIDATION_CHANNEL: ${ENV_MIRTH_VALIDATION_CHANNEL}
      MIRTH_METADATA_CHANNEL: ${ENV_MIRTH_METADATA_CHANNEL}
      LOGSPOUT: ignore  #ignore, because logs are forwarded by filebeat (in production it's not in a docker container)
      ENV_S3_ACCESS_KEY: ${ENV_S3_ACCESS_KEY1}
      ENV_S3_SECRET_KEY: ${ENV_S3_SECRET_KEY1}
      ENV_S3_RESC_NAME: "UM-Ceph-S3-AC"
      ENV_S3_HOST: "minio1.dh.local:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./irods.secrets.cfg:/etc/secrets:ro
      - ./externals/irods-ruleset:/rules
      - ./externals/irods-microservices:/microservices
      - ./externals/irods-helper-cmd:/helpers
    networks:
      default:
        aliases:
          - ires-s3-1.dh.local
      common_default:
        aliases:
          - ires-s3-1.dh.local

  ires-s3-2-based:
    image: irods-ires-s3:latest
    depends_on:
      - icat-based
      - ires-based  # Because of ingest resource
      - minio2
    hostname: ires-s3-2.dh.local
    environment:
      RODS_PASSWORD: irods
      VIRTUAL_HOST: ires-s3-2.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: ${ENV_IRODS_INGEST_REMOVE_DELAY}
      MIRTH_VALIDATION_CHANNEL: ${ENV_MIRTH_VALIDATION_CHANNEL}
      MIRTH_METADATA_CHANNEL: ${ENV_MIRTH_METADATA_CHANNEL}
      LOGSPOUT: ignore  #ignore, because logs are forwarded by filebeat (in production it's not in a docker container)
      ENV_S3_ACCESS_KEY: ${ENV_S3_ACCESS_KEY2}
      ENV_S3_SECRET_KEY: ${ENV_S3_SECRET_KEY2}
      ENV_S3_RESC_NAME: "UM-Ceph-S3-GL"
      ENV_S3_HOST: "minio2.dh.local:9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./irods.secrets.cfg:/etc/secrets:ro
      - ./externals/irods-ruleset:/rules
      - ./externals/irods-microservices:/microservices
      - ./externals/irods-helper-cmd:/helpers
    networks:
      default:
        aliases:
          - ires-s3-2.dh.local
      common_default:
        aliases:
          - ires-s3-2.dh.local

  ires-centos-based:
    image: irods-ires-centos:latest
    depends_on:
      - icat-based
    hostname: ires-centos.dh.local
    environment:
      RODS_PASSWORD: irods
      VIRTUAL_HOST: ires-centos.${RIT_ENV}.rit.unimaas.nl
      IRODS_INGEST_REMOVE_DELAY: ${ENV_IRODS_INGEST_REMOVE_DELAY}
      MIRTH_VALIDATION_CHANNEL: ${ENV_MIRTH_VALIDATION_CHANNEL}
      MIRTH_METADATA_CHANNEL: ${ENV_MIRTH_METADATA_CHANNEL}
      LOGSPOUT: ignore  #ignore, because logs are forwarded by filebeat (in production it's not in a docker container)
    networks:
      default:
        aliases:
          - ires-centos.dh.local
      common_default:
        aliases:
          - ires-centos.dh.local
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./irods.secrets.cfg:/etc/secrets:ro
      - ./externals/irods-ruleset:/rules
      - ./externals/irods-microservices:/microservices
      - ./externals/irods-helper-cmd:/helpers
      - ./staging-data:/mnt/ingest            # binding a non-existing dir results in creation of that dir on host system
    # Required for CIFS mounting. cap-add not enough in Windows for some reason.
    privileged: true
