server {
    listen 9000 ssl;
    server_name garage2.dh.local;

    ssl_certificate /etc/nginx/certs/garage2.dh.local.crt;
    ssl_certificate_key /etc/nginx/certs/garage2.dh.local.key;

    client_max_body_size 0;

    location / {
        proxy_pass http://garage2:3900;
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
    }
}
